# Generated by Django 4.2.7 on 2023-11-14 05:22

import builtins
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClassModel',
            fields=[
                ('id', models.BigIntegerField(db_column='id', primary_key=True, serialize=False)),
                ('name', models.TextField(db_column='name', max_length=255)),
                ('code', models.TextField(db_collation=builtins.ascii, db_column='code', max_length=50)),
                ('semester', models.TextField(db_column='semester', max_length=10)),
                ('subject_id', models.BigIntegerField(db_column='subject_id')),
                ('week', models.TextField(db_column='week', max_length=50)),
                ('day_of_week', models.TextField(db_column='day_of_week', max_length=50)),
                ('time_of_day', models.TextField(db_column='time_of_day', max_length=50)),
                ('is_assigned', models.SmallIntegerField(db_column='is_assigned')),
                ('teacher_id', models.BigIntegerField(db_column='teacher_id')),
                ('created_at', models.DateTimeField(db_column='created_at')),
                ('updated_at', models.DateTimeField(db_column='updated_at')),
            ],
            options={
                'db_table': 'class',
            },
        ),
        migrations.CreateModel(
            name='GroupTeacherMappingModel',
            fields=[
                ('id', models.BigIntegerField(db_column='id', primary_key=True, serialize=False)),
                ('teacher_id', models.BigIntegerField(db_column='teacher_id')),
                ('group_id', models.BigIntegerField(db_column='group_id')),
                ('role', models.TextField(db_column='role', max_length=500)),
            ],
            options={
                'db_table': 'group_teacher_mapping',
            },
        ),
        migrations.CreateModel(
            name='GroupTeacherModel',
            fields=[
                ('id', models.BigIntegerField(db_column='id', primary_key=True, serialize=False)),
                ('name', models.TextField(db_column='name', max_length=255)),
                ('description', models.TextField(db_column='description', max_length=1000)),
                ('leader', models.BigIntegerField(db_column='leader')),
                ('created_at', models.DateTimeField(db_column='created_at')),
                ('updated_at', models.DateTimeField(db_column='updated_at')),
            ],
            options={
                'db_table': 'group_teacher',
            },
        ),
        migrations.CreateModel(
            name='LanguageModel',
            fields=[
                ('id', models.BigIntegerField(db_column='id', primary_key=True, serialize=False)),
                ('name', models.TextField(db_column='name', max_length=100)),
                ('created_at', models.DateTimeField(db_column='created_at')),
                ('updated_at', models.DateTimeField(db_column='updated_at')),
            ],
            options={
                'db_table': 'language',
            },
        ),
        migrations.CreateModel(
            name='LanguageTeacherMappingModel',
            fields=[
                ('id', models.BigIntegerField(db_column='id', primary_key=True, serialize=False)),
                ('teacher_id', models.BigIntegerField(db_column='teacher_id')),
                ('language_id', models.BigIntegerField(db_column='language_id')),
            ],
            options={
                'db_table': 'language_teacher_mapping',
            },
        ),
        migrations.CreateModel(
            name='StudentProjectModel',
            fields=[
                ('id', models.BigIntegerField(db_column='id', primary_key=True, serialize=False)),
                ('name', models.TextField(db_column='name', max_length=100)),
                ('student_code', models.TextField(db_column='student_code', max_length=50)),
                ('class_id', models.BigIntegerField(db_column='class_id')),
                ('is_assigned', models.SmallIntegerField(db_column='is_assigned')),
                ('created_at', models.DateTimeField(db_column='created_at')),
                ('updated_at', models.DateTimeField(db_column='updated_at')),
                ('teacher_1_id', models.BigIntegerField(db_column='teacher_1_id')),
                ('teacher_2_id', models.BigIntegerField(db_column='teacher_2_id')),
                ('teacher_3_id', models.BigIntegerField(db_column='teacher_3_id')),
                ('teacher_assigned_id', models.BigIntegerField(db_column='teacher_assigned_id')),
            ],
            options={
                'db_table': 'student_project',
            },
        ),
        migrations.CreateModel(
            name='SubjectModel',
            fields=[
                ('id', models.BigIntegerField(db_column='id', primary_key=True, serialize=False)),
                ('name', models.TextField(db_column='name', max_length=255)),
                ('code', models.TextField(db_column='code', max_length=50)),
                ('group_id', models.BigIntegerField(db_column='group_id')),
                ('created_at', models.DateTimeField(db_column='created_at')),
                ('updated_at', models.DateTimeField(db_column='updated_at')),
            ],
            options={
                'db_table': 'subject',
            },
        ),
        migrations.CreateModel(
            name='TeacherModel',
            fields=[
                ('id', models.BigIntegerField(db_column='id', primary_key=True, serialize=False)),
                ('full_name', models.TextField(db_column='full_name', max_length=100)),
                ('rank_and_degree', models.TextField(db_column='rank_and_degree', max_length=50)),
                ('start_time', models.DateField(db_column='start_time')),
                ('birthday', models.DateField(db_column='birthday')),
                ('created_at', models.DateTimeField(db_column='created_at')),
                ('updated_at', models.DateTimeField(db_column='updated_at')),
            ],
            options={
                'db_table': 'teacher',
            },
        ),
    ]
