# Generated by Django 4.2.7 on 2023-11-06 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherModel',
            fields=[
                ('id', models.BigIntegerField(db_column='id', primary_key=True, serialize=False)),
                ('full_name', models.TextField(db_column='full_name', max_length=100)),
                ('rank_and_degree', models.TextField(db_column='rank_and_degree', max_length=50)),
                ('start_time', models.DateField(db_column='start_time')),
                ('birthday', models.DateField(db_column='birthday')),
                ('created_at', models.DateTimeField(db_column='created_at')),
                ('updated_at', models.DateTimeField(db_column='updated_at')),
            ],
            options={
                'db_table': 'teacher',
            },
        ),
    ]
