# Generated by Django 4.2.7 on 2023-12-19 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classmodel',
            name='language_id',
            field=models.BigIntegerField(db_column='language_id', default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='classmodel',
            name='time_of_class',
            field=models.IntegerField(db_column='time_of_class', default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teachermodel',
            name='gd_time',
            field=models.IntegerField(db_column='gd_time', default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teachermodel',
            name='hd_time',
            field=models.IntegerField(db_column='hd_time', default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teachermodel',
            name='rating',
            field=models.FloatField(db_column='rating', default=0),
            preserve_default=False,
        ),
    ]
